### ISSUE TITLE
Segmentation fault with primeList and primeSieve

### ISSUE THREAD

**Issue by treeowl** [mietek/arithmoi#1]
I've filed a report in the official tracker, but the maintainer doesn't exactly seem to be around these days, so I'll file one here too in case you want to look into it.

```haskell
primesSumWonk :: Int -> Int
primesSumWonk upto = sum . takeWhile (< upto) . map fromInteger . primeList $ primeSieve (toInteger upto)

primesSum :: Int -> Int
primesSum upto = sum . takeWhile (< upto) . map fromInteger $ primes

main = do
  hspec $
    describe "Primes.primesSumWonk" $
      it "works like primesSum" $
        property $ \n -> let upto = abs (n `rem` 45)
                         in primesSum upto == primesSumWonk upto
```

Run several times with `-a 100000` or so, and at some point it'll randomly die with a segmentation violation.

**Comment by mietek** [comment]
Was this with LLVM on or off?

-- 
Miëtek

**Comment by treeowl** [comment]
I think both ways,  but I'm not sure I turned it off correctly.

**Comment by treeowl** [comment]
Let me know if you can reproduce it.

**Comment by mietek** [comment]
Full reproduction instructions:

```
$ cabal sandbox init
$ cabal install arithmoi-0.4.1.1 hspec-2.1.2
$ cat >Spec.hs <<'EOF'
```
```haskell
import Test.Hspec
import Test.QuickCheck
import Math.NumberTheory.Primes

primesSumWonk :: Int -> Int
primesSumWonk upto = sum . takeWhile (< upto) . map fromInteger . primeList $ primeSieve (toInteger upto)

primesSum :: Int -> Int
primesSum upto = sum . takeWhile (< upto) . map fromInteger $ primes

main = do
  hspec $
    describe "Primes.primesSumWonk" $
      it "works like primesSum" $
        property $ \n -> let upto = abs (n `rem` 45)
                         in primesSum upto == primesSumWonk upto
````
```
EOF
$ cabal exec runhaskell Spec.hs

Primes.primesSumWonk
Segmentation fault (core dumped)
```

**Comment by treeowl** [comment]
FYI, if you do decide to attempt to fix this, you might look at making it use the `bitvec` package for mutable bit vectors instead of weaving that junk into the prime sieve in a way that leaves me utterly baffled about just what it's supposed to be doing. Another very pleasant alternative might be to just steal sieves from the `NumberSieves` package. I have no idea about how their performance compares, theoretically, but anything is better than code that's blatantly *broken*.

**Comment by mietek** [comment]
@cartazio is the new official maintainer, so I’ve moved this to https://github.com/cartazio/arithmoi/issues/2.
